### ISSUE TITLE
Blueprints: automation settings are not saved

### ISSUE THREAD

**Issue by admilazz** [0Mayall/ONIMods#11]
I installed the Blueprints mod for the first time a couple days ago. It's very helpful, but one problem is that automation settings are not saved. When I use a blueprint, they are reset to the defaults.

**Comment by 0Mayall** [comment]
This isn't a feature. It's something I'd like to add but it'll be a real big addition.

**Comment by admilazz** [comment]
I see. Good to know. Thanks for your work.
