### ISSUE TITLE
MOD manager issues

### ISSUE THREAD

**Issue by TheMule71** [0Mayall/ONIMods#6]
Hi, I don't know which is your preferred way for us to report issues, so I'm also writing here sorry for duplication.

This is what I posted on Steam.
I have disabled the MOD manager, disabled pliers, quit the game, unsubscribed from the workshop page. Resubscribed, enabled pliers, restared. In the mod list it's still v1.1.64.0 but it works in game. So the wrong version is not a MOD manager problem.

If I try and reenable MOD manager, it still crashes. Has it anything with to do with the version checking maybe?

**Comment by baranowb** [comment]
Same here. If I enable it and just play game, pliers and blueprints work fine. But if I enter mod manager - booom. lag spike, mods unlist and ONI begs for restart. Only in my case version in mod list/manager are up2date( checked against repo tags).

Ping me if you need log.

**Comment by TroublesomeCorvid** [comment]
Same here.  Ony claims it's not her Mod's fault.  I'll believe it once someone else claims fault or you and Ony put your heads together on this and figure it out.  Personally?  I think that with the way the output log keeps flagging Mod Manager with the errors, the blame is shared here.

Output log attached.
[output_log_part_1.txt](https://github.com/0Mayall/ONIMods/files/4321818/output_log_part_1.txt)


Output log attached.

**Comment by 0Mayall** [comment]
I cannot fix the issue with this as it's on her mod's end. Her code doesn't even try to mitigate risk; expecting everything to work in an incredibly specific way. It's rigid and frankly poorly written.

I do apologise if I sound angered but to be frank I'm sick of how she behaves. People tried to reach out to her and she won't try to fix the issue.
